// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMKqd9ONRmTQtyLHTnIY0kwEz83py-hxo',
    appId: '1:679921457730:web:6fd566d9ffc761295d2bdb',
    messagingSenderId: '679921457730',
    projectId: 'scholar-chat-d871a',
    authDomain: 'scholar-chat-d871a.firebaseapp.com',
    storageBucket: 'scholar-chat-d871a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz7dicyZ53sTfA092qIPIasrQ4XWJ45b0',
    appId: '1:679921457730:android:fda00d2652e809755d2bdb',
    messagingSenderId: '679921457730',
    projectId: 'scholar-chat-d871a',
    storageBucket: 'scholar-chat-d871a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YfYM9JT3UDc-ixWbPuqUcc2RaHy-e50',
    appId: '1:679921457730:ios:10fa46a02c773e8d5d2bdb',
    messagingSenderId: '679921457730',
    projectId: 'scholar-chat-d871a',
    storageBucket: 'scholar-chat-d871a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7YfYM9JT3UDc-ixWbPuqUcc2RaHy-e50',
    appId: '1:679921457730:ios:10fa46a02c773e8d5d2bdb',
    messagingSenderId: '679921457730',
    projectId: 'scholar-chat-d871a',
    storageBucket: 'scholar-chat-d871a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMKqd9ONRmTQtyLHTnIY0kwEz83py-hxo',
    appId: '1:679921457730:web:091a4d9314fd63765d2bdb',
    messagingSenderId: '679921457730',
    projectId: 'scholar-chat-d871a',
    authDomain: 'scholar-chat-d871a.firebaseapp.com',
    storageBucket: 'scholar-chat-d871a.firebasestorage.app',
  );
}
